name: CI / Build / Test / Auto-Merge

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build frontend (matrix)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: build-npm-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-npm-${{ matrix.node-version }}-

      - name: Install backend dependencies
        run: npm ci

      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Build frontend
        run: npm run build --prefix frontend

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist-${{ matrix.node-version }}
          path: frontend/dist

  test:
    name: Test (matrix)
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test --if-present
        env:
          NODE_ENV: test

      - name: Run Playwright tests
        run: |
          npx playwright install --with-deps
          npx playwright test
        env:
          NODE_ENV: test

  pr_merge:
    name: Create PR & Auto-merge (feature → main)
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event_name == 'push' && github.ref != 'refs/heads/main'

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or find PR from feature branch to main
        id: create_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = process.env.GITHUB_REF.replace('refs/heads/','');
            const base = 'main';
            // Search for existing open PR
            const existing = await github.rest.pulls.list({ owner, repo, head: `${owner}:${head}`, base, state: 'open' });
            if (existing.data.length) {
              console.log(`Found existing PR #${existing.data[0].number}`);
              return { pr_number: existing.data[0].number };
            }
            const pr = await github.rest.pulls.create({ owner, repo, head, base, title: `Auto PR: ${head} → ${base} (CI)`, body: `Automated PR created by CI: ${head} → ${base}. Build+Tests passed.` });
            console.log(`Created PR #${pr.data.number}`);
            return { pr_number: pr.data.number };

      - name: Capture PR number
        if: ${{ steps.create_pr.outputs.pr_number != '' }}
        run: |
          echo "pr_number=${{ steps.create_pr.outputs.pr_number }}" >> $GITHUB_OUTPUT

      - name: Attempt to merge PR automatically
        if: ${{ steps.create_pr.outputs.pr_number != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = parseInt(process.env.PR_NUMBER || process.env.PR_NUMBER_FALLBACK || '', 10) || parseInt(core.getInput('pr_number', { required: false }) || '', 10);
            if (!pull_number) {
              console.warn('No PR number available to merge');
              return;
            }
            try {
              await github.rest.pulls.merge({ owner, repo, pull_number, merge_method: 'merge' });
              console.log(`PR #${pull_number} merged successfully.`);
            } catch (err) {
              console.warn(`Auto-merge failed: ${err.message}`);
              try { await github.rest.pulls.update({ owner, repo, pull_number, body: `Auto-merge attempted but blocked: ${err.message}. Build+Tests succeeded.` }); } catch(e) { console.warn('Could not update PR body:', e.message); }
            }
        env:
          PR_NUMBER: ${{ steps.create_pr.outputs.pr_number }}
